name: release
 
on:
  push:
    branches:
      - master
 
jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout 
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: test
        run: |
          npm install
