name: review
 
on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  review:
    timeout-minutes: 30
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout 
        uses: actions/checkout@v4
 
      - name: project-version-check (integration-test)
        id: actions_project_version_check
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: package.json
          additional-files-to-check: README.md

      - name: project-version-output-check
        run: |
          if [ -z "${{ steps.actions_project_version_check.outputs.version }}" ] 
          then
            exit 1
          fi

      - name: get-project-version (integration-test)
        id: actions_project_version_check_get
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: package.json
          only-return-version: true

      - name: get-project-version-output-check
        run: |
          if [ -z "${{ steps.actions_project_version_check_get.outputs.version }}" ] 
          then
            exit 1
          fi

      - name: test
        run: |
          npm install
